# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
      
  deploy:
   runs-on: ubuntu-latest
   needs: build
   steps:
    - name: Deploy to EC2
      env:
         EC2_KEY: ${{ secrets.EC2_PEM }}
      run: |
        echo "${EC2_KEY}" > "key.pem"
        chmod 400 key.pem  
        ssh -i "key.pem" -o StrictHostKeyChecking=no ubuntu@ec2-3-111-32-69.ap-south-1.compute.amazonaws.com << 'EOF'
          # Install Go if it's not installed
          if ! command -v go &> /dev/null; then
            echo "Go not found. Installing Go..."
            wget https://go.dev/dl/go1.20.8.linux-amd64.tar.gz
            sudo tar -C /usr/local -xzf go1.20.8.linux-amd64.tar.gz
            echo 'export PATH=$PATH:/usr/local/go/bin' >> ~/.bashrc
            source ~/.bashrc
          fi
          
          # Go to project directory and run the application
          cd Unit_testing1
          git pull
          go run main.go
          exit
        EOF


