# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
      
  deploy:
   runs-on: ubuntu-latest
   needs: build
   steps:
    - name: Deploy to EC2
      env:
         EC2_KEY: ${{ secrets.EC2_PEM }}
      run: |
        echo "${EC2_KEY}" > "key.pem"
        chmod 400 key.pem  
        ssh -i "key.pem" -o StrictHostKeyChecking=no ubuntu@ec2-3-111-32-69.ap-south-1.compute.amazonaws.com << 'EOF'
          # Kill any process running on port 8080
          sudo fuser -k 8080/tcp
          
          # Ensure Go is available
          export PATH=$PATH:/usr/local/go/bin
          
          # Go to project directory and pull the latest code
          cd Unit_testing1
          git pull

          # Run the server in the background
          nohup go run main.go &
        EOF




